# Configuración de Netlify para Radio App (Angular 16)
# ========================================================

# Configuración de Build
[build]
  # Comando para compilar la aplicación en modo producción
  command = "npm ci && npm run build:prod"
  
  # Directorio donde se encuentran los archivos compilados
  publish = "dist/radio-app"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "18"

# Redirects y Rewrites para SPA (Single Page Application)
# ========================================================
# Esto es CRÍTICO para que Angular Router funcione correctamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
  # Excepciones: No redirigir archivos estáticos
  conditions = {Not = ["/assets/*", "/*.js", "/*.css", "/*.svg", "/*.png", "/*.jpg", "/*.jpeg", "/*.gif", "/*.ico", "/*.woff", "/*.woff2", "/*.ttf", "/*.eot"]}

# Headers de Seguridad
# ========================================================
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (CSP)
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com data:;
      img-src 'self' data: https: http:;
      media-src 'self' https: http: blob:;
      connect-src 'self' https://de1.api.radio-browser.info https://at1.api.radio-browser.info https://nl1.api.radio-browser.info wss:;
      frame-src 'none';
      object-src 'none';
    """
    
    # Permissions Policy (antes Feature-Policy)
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Headers para Assets Estáticos (Cache Agresivo)
# ========================================================
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para Fuentes
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers para index.html (Sin cache)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Optimizaciones de Build
# ========================================================
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugins de Netlify (Opcional)
# ========================================================
# Descomentar si necesitas estas funcionalidades

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   
#   [plugins.inputs]
#     output_path = "reports/lighthouse.html"

# [[plugins]]
#   package = "netlify-plugin-checklinks"
#   
#   [plugins.inputs]
#     skipPatterns = ["*/admin/*"]

# Configuración de Deploy Contexts
# ========================================================

# Producción (rama main)
[context.production]
  command = "npm ci && npm run build:prod"
  
  [context.production.environment]
    NODE_ENV = "production"

# Vista previa de Pull Requests
[context.deploy-preview]
  command = "npm ci && npm run build:prod"
  
  [context.deploy-preview.environment]
    NODE_ENV = "preview"

# Rama de desarrollo
[context.branch-deploy]
  command = "npm run build"
  
  [context.branch-deploy.environment]
    NODE_ENV = "development"

# Redirects Adicionales (Ejemplos comentados)
# ========================================================

# Redirigir versión www a no-www
# [[redirects]]
#   from = "https://www.tu-dominio.com/*"
#   to = "https://tu-dominio.com/:splat"
#   status = 301
#   force = true

# Redirigir dominio antiguo
# [[redirects]]
#   from = "https://old-domain.com/*"
#   to = "https://new-domain.com/:splat"
#   status = 301
#   force = true

# API Proxy (si necesitas ocultar URL de backend)
# [[redirects]]
#   from = "/api/*"
#   to = "https://tu-backend.com/api/:splat"
#   status = 200
#   force = true
#   headers = {X-From = "Netlify"}
